### ISSUE TITLE
Failed on Lrnr_solnp_TRUE_TRUE_FALSE_400_800_1e-07_1e-08_FALSE

### ISSUE THREAD

**Issue by WenxinZhang25** [tlverse/tmle3mopttx#11]
Hi Ivana,

Thanks for providing this excellent package! I am meeting an issue when running testthat/test_categorical_rule.R:

> Failed on Lrnr_solnp_TRUE_TRUE_FALSE_400_800_1e-07_1e-08_FALSE
> Error in if (max(c(tol + tt[1], tt[2] - tt[3])) <= 0) { : 
>   missing value where TRUE/FALSE needed

Do you have any idea about how to avoid this error? Thanks!

**Comment by imalenica** [comment]
Hm, I am not getting this error. It looks like the metalearnering step is failing based on the error message.  Can you run it step by step and let me know where it fails?

tmle_task <- tmle_spec$make_tmle_task(data, node_list)
initial_likelihood <- tmle_spec$make_initial_likelihood(tmle_task, learner_list)
updater <- tmle_spec$make_updater()
targeted_likelihood <- tmle_spec$make_targeted_likelihood(initial_likelihood, updater)
tmle_params <- tmle_spec$make_params(tmle_task, likelihood=targeted_likelihood)
fit <- fit_tmle3(tmle_task, targeted_likelihood, tmle_params, updater)

**Comment by WenxinZhang25** [comment]
I found the error happens at the step of fitting the initial likelihood. I am using the latest version of sl3, tmle3 and tmle3mopttx.

> initial_likelihood <- tmle_spec$make_initial_likelihood(tmle_task, learner_list)

> traceback() 
7: stop(first_error$value) 
6: self$compute_step() 
5: scheduler$compute() 
4: delayed_fit$compute(job_type = sl3_delayed_job_type(), progress = verbose) 
3: likelihood_def$train(tmle_task) 
2: point_tx_likelihood(tmle_task, learner_list) 
1: tmle_spec$make_initial_likelihood(tmle_task, learner_list)

But when I degrade my sl3 from v1.4.4 to v1.4.2, I could run the code only with warnings in the initial_likelihood step

> [18:39:28] WARNING: amalgamation/../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.

and with some error messages in fit_tmle3 step as belows. And finally I got an estimate of mean of ITR.

> Error in xgboost::xgb.DMatrix(Xmat) : 
  xgb.DMatrix does not support construction from double
Error in if (nrow(Xmat) > 0) { : argument is of length zero
Failed on predict
Error in self$compute_step() : 
  Error in if (nrow(Xmat) > 0) { : argument is of length zero

And finally I got an estimate of mean of ITR.

>     type         param init_est  tmle_est         se    lower     upper psi_transformed lower_transformed upper_transformed
> 1:  TSM E[Y_{d(V=1)}] 0.471865 0.5825754 0.09650095 0.393437 0.7717138       0.5825754          0.393437         0.7717138
>

**Comment by imalenica** [comment]
Thanks for pointing this out! I have to check what was added to sl3 that could be causing this issue; must me something with the multivariate learner.  

For the older version, It looks like xgboost is failing for this task, but it has other learners hence you still have an estimate.

**Comment by jvpoulos** [comment]
fwiw, I get the same error from the multivariate metalearner after upgrading sl3 to v1.4.4

**Comment by imalenica** [comment]
Thank you for pointing out the error. The current version of tmle3mopttx should be compatible with the latest version of sl3 now.
